DIR_PROJECT_ROOT=".."
DIR_CMAKE_TOOLCHAIN=${DIR_PROJECT_ROOT}/cmake/toolchain
CMAKE_CROSS_COMPILE_FLAG="-DCMAKE_TOOLCHAIN_FILE=${DIR_CMAKE_TOOLCHAIN}/MinGWCross.cmake"


cmake ${CMAKE_CROSS_COMPILE_FLAG} ${DIR_PROJECT_ROOT}
